services:

  db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: wallet-redis
    ports:
      - "6379:6379"
  # app:
  #   build: .
  #   container_name: wallet-app
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/walletdb
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379