spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false